image: registry-cybermiles.skymizer.com/cybermiles/environment:ci

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@git-cybermiles.skymizer.com/".insteadOf https://git-cybermiles.skymizer.com/
  - git submodule update --init

build:
  stage: build
  script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j8
    - cd ..
    - rm -rf aleth
    - cp build/aleth/aleth .
  artifacts:
    paths:
      - aleth
    expire_in: 1 month
